#In order to copy to/from the volume, you must be located in it. I don't know exactly why, but Linux is a bit strange with things like this sometimes:
#cd /tmp/vol
---
- name: Attach volume
  hosts: localhost

  tasks:
  - name: Attaching volume to ansible
    os_server_volume:
      state: present
      server: Ansibleserver1
      volume: File_storage
      device: /dev/sdb

  - name: Mounting the volume
    become: true
    mount:
      path: /tmp/vol
      src: /dev/sdb
      fstype: ext4
      state: mounted
