---
- name: Backup acmedb database
  hosts: "{{ mountserver }}"
  become: true
  vars_files:
    - mount-server-vars.yml
  
  tasks:
    - name: test
      shell: mysqldump -u root acmedb > /tmp/vol/backup.sql

