---
- name: Create OpenStack instances
  hosts: localhost
  vars_files:
    - ../vars-etc/instances-vars.yml
    - ../vars-etc/private-vars.yml
  tasks:
  - name: "{{ setupweb }}1"
    os_server:
      name: Webserver1
      state: present
      region_name: RegionOne
      image: Ubuntu server 20.04
      availability_zone: Education
      key_name: "{{ key_name }}"
      network: "{{ network }}"
      auto_ip: false
      flavor: c2-r4-d10
      security_groups:
         - SSH
         - default      

  - name: "{{ setupweb }}2"
    os_server:
      name: Webserver2
      state: present
      region_name: RegionOne
      image: Ubuntu server 20.04
      availability_zone: Education
      key_name: "{{ key_name }}"
      network: "{{ network }}"
      auto_ip: false
      flavor: c2-r4-d10
      security_groups:
         - SSH
         - default  
      
  - name: "{{ setupweb }}3"
    os_server:
      name: Webserver3
      state: present
      region_name: RegionOne
      image: Ubuntu server 20.04
      availability_zone: Education
      key_name: "{{ key_name }}"
      network: "{{ network }}"
      auto_ip: false
      flavor: c2-r4-d10
      security_groups:
         - SSH
         - default
      
  - name: "{{ setupnginx }}"
    os_server:
      name: NGINX/loadbalancer
      state: present
      region_name: RegionOne
      image: Ubuntu server 20.04
      availability_zone: Education
      key_name: "{{ key_name }}"
      network: "{{ network }}"
      auto_ip: true
      flavor: c2-r4-d10
      security_groups:
         - SSH
         - default  
         - Loadbalancer 
      
  - name: "{{ setupfile }}"
    os_server:
      name: File_server
      state: present
      region_name: RegionOne
      image: Ubuntu server 20.04
      availability_zone: Education
      key_name: "{{ key_name }}"
      network: "{{ network }}"
      auto_ip: false
      flavor: c2-r4-d10
      security_groups:
         - SSH
         - default
      
  - name: "{{ setupdbmaster }}"
    os_server:
      name: DB_master
      state: present
      region_name: RegionOne
      image: Ubuntu server 20.04
      availability_zone: Education
      key_name: "{{ key_name }}"
      network: "{{ network }}"
      auto_ip: false
      flavor: c2-r4-d10
      security_groups:
         - SSH
         - default      
      
  - name: "{{ setupdbslave }}"
    os_server:
      name: DB_slave
      state: present
      region_name: RegionOne
      image: Ubuntu server 20.04
      availability_zone: Education
      key_name: "{{ key_name }}"
      network: "{{ network }}"
      auto_ip: false
      flavor: c2-r4-d10
      security_groups:
         - SSH
         - default
     
  - name: "{{ setupmonitoring }}"
    os_server:
      name: Monitoring
      state: present
      region_name: RegionOne
      image: Ubuntu server 20.04
      availability_zone: Education
      key_name: "{{ key_name }}"
      network: "{{ network }}"
      auto_ip: true
      flavor: c2-r4-d10
      security_groups:
         - SSH
         - default 
         - Monitoring



