---
- name: Create dynamic inventory
  hosts: localhost
  tasks:

#Ansible
    - name: Remove old inventory.yml file
      file:
        path: "/home/ubuntu/Playbooks/vars-etc/inventory.yml"
        state: absent

    - name: Create inventory.yml file
      file:
        path: "/home/ubuntu/Playbooks/vars-etc/inventory.yml"
        state: touch

    - name: Get ip for Ansible
      shell: ../openstack_inventory.py --host Ansibleserver1
      register: result
    - set_fact:
        myvar: "{{ result.stdout | from_json }}"     
    - lineinfile: 
        path: ../vars-etc/inventory.yml 
        line: "[ansible]"
        insertbefore: EOF
    - lineinfile: 
        path: ../vars-etc/inventory.yml 
        line: Ansibleserver1 ansible_host={{myvar.private_v4}}
        insertbefore: EOF
#Nginx
    - name: Get ip for NGINX/loadbalancer
      shell: ../openstack_inventory.py --host NGINX/loadbalancer
      register: result
    - set_fact:
        myvar: "{{ result.stdout | from_json }}"     
    - lineinfile:
        path: ../vars-etc/inventory.yml    
        line: "\n[nginx]"
        insertbefore: EOF
    - lineinfile:
        path: ../vars-etc/inventory.yml
        line: Nginx ansible_host={{myvar.private_v4}} floating_ip={{myvar.public_v4}}
        insertbefore: EOF

#DB_master
    - name: Get ip for DB_master
      shell: ../openstack_inventory.py --host DB_master
      register: result
    - set_fact:
        myvar: "{{ result.stdout | from_json }}" 
    - lineinfile: 
        path: ../vars-etc/inventory.yml 
        line: "\n[databases]"
        insertbefore: EOF
    - lineinfile: 
        path: ../vars-etc/inventory.yml 
        line: DB_master ansible_host={{myvar.private_v4}}
        insertbefore: EOF

#DB_slave
    - name: Get ip for DB_slave
      shell: ../openstack_inventory.py --host DB_slave
      register: result
    - set_fact:
        myvar: "{{ result.stdout | from_json }}" 
    - lineinfile: 
        path: ../vars-etc/inventory.yml 
        line: DB_slave ansible_host={{myvar.private_v4}}
        insertbefore: EOF

#Monitoring    
    - name: Get ip for Monitoring
      shell: ../openstack_inventory.py --host Monitoring
      register: result
    - set_fact:
        myvar: "{{ result.stdout | from_json }}" 
    - lineinfile: 
        path: ../vars-etc/inventory.yml 
        line: "\n[monitoring]"
        insertbefore: EOF
    - lineinfile: 
        path: ../vars-etc/inventory.yml 
        line: Monitoring ansible_host={{myvar.private_v4}}
        insertbefore: EOF

#File_server
    - name: Get ip for File server
      shell: ../openstack_inventory.py --host File_server
      register: result
    - set_fact:
        myvar: "{{ result.stdout | from_json }}" 
    - lineinfile: 
        path: ../vars-etc/inventory.yml 
        line: "\n[file_servers]"
        insertbefore: EOF
    - lineinfile: 
        path: ../vars-etc/inventory.yml 
        line: File_server ansible_host={{myvar.private_v4}}
        insertbefore: EOF

#Webserver1
    - name: Get ip for Webserver1
      shell: ../openstack_inventory.py --host Webserver1
      register: result
    - set_fact:
        myvar: "{{ result.stdout | from_json }}"
    - lineinfile:
        path: ../vars-etc/inventory.yml
        line: "\n[webservers]"
        insertbefore: EOF
    - lineinfile:
        path: ../vars-etc/inventory.yml
        line: Webserver1 ansible_host={{myvar.private_v4}}
        insertbefore: EOF

#Webserver2
    - name: Get ip for Webserver2
      shell: ../openstack_inventory.py --host Webserver2
      register: result
    - set_fact:
        myvar: "{{ result.stdout | from_json }}"
    - lineinfile:
        path: ../vars-etc/inventory.yml
        line: Webserver2 ansible_host={{myvar.private_v4}}
        insertbefore: EOF

#Webserver3
    - name: Get ip for Webserver3
      shell: ../openstack_inventory.py --host Webserver3
      register: result
    - set_fact:
        myvar: "{{ result.stdout | from_json }}"
    - lineinfile:
        path: ../vars-etc/inventory.yml
        line: Webserver3 ansible_host={{myvar.private_v4}}
        insertbefore: EOF
