---
- hosts: localhost
  tasks:
    - name: Get ip to upscaled server
      shell: grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' /home/ubuntu/Playbooks/vars-etc/inventory.yml | tail -1 > /tmp/newip.txt

    - name: Copy file to nginx-server
      shell: scp -i ~/.ssh/acme-key.pem /tmp/newip.txt ubuntu@{{ hostvars.Nginx.ansible_host }}:/tmp/

- hosts: nginx
  become: yes

  tasks:
    - name: Create variable
      shell: grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' /tmp/newip.txt
      register: command_output

    - name: Add serverip to nginxconfig
      shell: sed -i '/least_conn/a server {{ command_output.stdout }}:80 weight=1 ;' /etc/nginx/conf.d/default.conf
