---
- name: Create OpenStack instances
  hosts: localhost
  vars_files:
    - ../vars-etc/instances-vars.yml
    - ../vars-etc/private-vars.yml

  tasks:
    - name: "{{ setupansible }}"
      os_server:
        name: Ansibleserver1
        state: present
        region_name: RegionOne
        image: Ubuntu server 20.04
        availability_zone: Education
        key_name: "{{ key_name }}"
        network: "{{ network }}"
        auto_ip: true
        flavor_ram: 1024
        security_groups:
          - SSH
          - default
    
    - name: Pause for 40 secs to allow Ansibleserver1 to complete its startup
      pause:
        seconds: 40

- name: initialize-inventory.yml
  import_playbook: initialize-local-inventory.yml



#    ToDo: Create a snapshot of the clean Ansible server
#    ToDo: Maybe transfer automatic the Script to the new server.
#    ToDo: Even better to create a snapshot automatic.
