---
- hosts: localhost
  
- name: Network Up
  import_playbook: network-up.yml

- name: Security Groups Up
  import_playbook: security-groups-up.yml

- name: Ansible Up
  import_playbook: ansible-instance-up.yml

