---
- name: Tear down Openstack network infrastructure
  hosts: localhost
  vars_files:
    - ../vars-etc/network-vars.yml
  tasks:
        - name: Delete router
          os_router:
            name: "{{ routername }}"
            state: absent

        - name: Delete subnet
          os_subnet:
            name: "{{ subnetworkname }}"
            network_name: "{{ networkname }}"
            state: absent

        - name: Delete network
          os_network:
            name: "{{ networkname }}"
            state: absent

        - name: Delete security group
          os_security_group:
            name: SSH
            state: absent
