---
- name: Create Openstack network infrastructure
  hosts: localhost
  vars_files:
    - ../vars-etc/network-vars.yml
  tasks:
        - name: Create network
          os_network:
            name: "{{ networkname }}"
            validate_certs: yes
            state: present

        - name: Create subnet
          os_subnet:
            name: "{{ subnetworkname }}"
            network_name: "{{ networkname }}"
            cidr: "{{ iprange }}"
            allocation_pool_start: 192.168.0.2
            allocation_pool_end: 192.168.0.32
            dns_nameservers:
              - 8.8.8.8
              - 8.8.4.4
            enable_dhcp: yes
            validate_certs: yes
            state: present

        - name: Create router
          os_router:
            name: "{{ routername }}"
            network: public
            interfaces: "{{ subnetworkname }}"
            state: present
            
        - name: Create SSH Security Group
          os_security_group:
            state: present
            name: SSH
            description: SSH security group
            
        - name: Add SSH rule
          os_security_group_rule:
            security_group: SSH
            protocol: tcp
            port_range_min: 22
            port_range_max: 22
            remote_ip_prefix: 0.0.0.0/0 

