- name: Create OpenStack instance
  hosts: localhost
  tasks:
    - name: Deploy an instance
      os_server:
        name: testinstance
        state: present
        region_name: RegionOne
        image: Ubuntu server 20.04
        availability_zone: Education
        network: "test"
        auto_ip: yes
        flavor_ram: 4096
