---
- name: Configure MySQL master
  become: yes
  hosts: DB_master
  tasks:
    - name: Configure bind-address
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address  = {{ hostvars.DB_master.ansible_host }}'
        backrefs: yes

    - name: Configure server-id
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertafter: EOF
        line: 'server-id   =1'

    - name: Add binlog_do_db
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertafter: EOF
        line: binlog_do_db = acmedb

    - name: Add log-configuration
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertafter: EOF
        line: 'log_bin = /var/log/mysql/mysql-bin.log'

    - name: Add log-configuration
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertafter: EOF
        line: 'log_bin_index =/var/log/mysql/mysql-bin.log.index'

    - name: Add log-configuration
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertafter: EOF
        line: 'relay_log = /var/log/mysql/mysql-relay-bin'

    - name: Add log-configuration
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertafter: EOF
        line: 'relay_log_index = /var/log/mysql/mysql-relay-bin.index'

    - name: Restart mysql
      service:
        name: mysql
        state: restarted

    - name: Run configuration script DB_master
      script: ~/Scripts/dbmaster.sh {{ hostvars.DB_slave.ansible_host }} {{ hostvars.Webserver1.ansible_host }} {{ hostvars.Webserver2.ansible_host }} {{ hostvars.Webserver3.ansible_host }}

- hosts: localhost
  tasks:
    - name: Copy variable file from DB_master
      shell: scp -i ~/.ssh/2dv517-lm222qm.pem ubuntu@{{ hostvars.DB_master.ansible_host }}:~/masterstatus.yml ~/Playbooks/vars-etc/

