---
- name: Configure MySQL master
  become: yes
  hosts: DB_master
  tasks:
    - name: Configure bind-address
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address  = {{ hostvars.DB_master.ansible_host }}'
        backrefs: yes

    - name: Configure server-id
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertafter: EOF
        line: 'server-id   =1'

    - name: Add binlog_do_db
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertafter: EOF
        line: binlog_do_db = acmedb

    - name: Add log-configuration
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertafter: EOF
        line: 'log_bin = /var/log/mysql/mysql-bin.log'

    - name: Add log-configuration
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertafter: EOF
        line: 'log_bin_index =/var/log/mysql/mysql-bin.log.index'

    - name: Add log-configuration
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertafter: EOF
        line: 'relay_log = /var/log/mysql/mysql-relay-bin'

    - name: Add log-configuration
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertafter: EOF
        line: 'relay_log_index = /var/log/mysql/mysql-relay-bin.index'

#    - name: Create database user
 #     shell: mysql -u root -e 'CREATE USER 'replication_user'@'{{ hostvars.DB_master.ansible_host }}' IDENTIFIED BY 'replica_password';'
#
 #   - name: Give user all database privileges
  #    shell: mysql -u root -e 'GRANT REPLICATION SLAVE ON *.* TO 'replication_user '@'{{ hostvars.DB_master.ansible_host }}';'

#    - name: Install community mysql
#      shell: ansible-galaxy collection install community.mysql
#
#    - name: Create database user with all database privileges
 #     community.mysql.mysql_user:
  #      name: replication_user
   ##   state: present
   # ALTER USER myuser IDENTIFIED WITH mysql_native_password BY 'mypassword';