---
- name: MySQL
  become: yes
  remote_user: ubuntu
  hosts: databases
  tasks:
    - name: Install MySQL server
      package: name=mysql-server update_cache=yes state=latesudio
    - name: Install MySQL client
      package: name=mysql-client state=latest
