---
- hosts: localhost

- name: Ansible down
  import_playbook: ansible-instance-down.yml

- name: Infrastructure down
  import_playbook: infrastructure_down.yml

- name: Network down
  import_playbook: network-down.yml
