---
- hosts: localhost

- name: Network Up
  import_playbook: network-up.yml

- name: Ansible Up
  import_playbook: ansible-instance-up.yml


- name: Infrastructure Up
  import_playbook: infrastructure_up.yml

